### PR TITLE
dev: change dependence in requirements.txt setup.py and tox.ini

### PR DESCRIPTION
**Pull request by liangxin1300**
BTW, crmsh.spec file may not be latest(version is 2.3.0) so I don't known whether should I change it

### CODE REVIEW

**Comment by krig** [comment]
I can update the spec file, I have a new one.

**Comment by liangxin1300** [comment]
So, after resolve the issues about travis CI, we can merge this tree to master,
Is that right?

**Comment by krig** [comment]
I think would be OK to merge to master even if Travis CI is broken for the moment, and tag as a 3.1 preview release.
Fixing Travis CI might take some time.

**Comment by liangxin1300** [comment]
OK, I will continue to create PRs to master from my [NewCommit tree](https://github.com/liangxin1300/crmsh/tree/crmsh-py3-newcommits) with more descriptions when master is done:)

**Pull request merged**
