### PR TITLE
crmsh py2->py3 migration 

### PR DESCRIPTION
**Pull request by liangxin1300**
Hi @krig,

   This pull request include all of changes about py2->py3 migration for crmsh.

   There are some conflicts because I have done some git-rebase work;
   If you want to merge, please reset py3-2017 tree to commit **24bb0ee** :)
  
   Primary changes include:
   * drop the compatible codes for py2
   * convert bytes to str
   * convert str to bytes
   * hb_report codes and it's py3 migration patches
   * fate#321640 codes and it's py3 migration patches

   Please help me for reviewing these works :)
   Any suggestions are welcome.
   Thank you!

   Regards,
   xin

### CODE REVIEW

**Comment by liangxin1300** [comment]
And, during doing migration job, I also created some other commits which just related with crmsh's logic.
These other new commits based on my [tree](https://github.com/liangxin1300/crmsh/tree/crmsh-py3-newcommits).

I will add some descriptions to explain why to do that on each of them, after you've done above review works

Regards,
xin

**Comment by krig** [comment]
Hi Xin, should I look at this code or just look at your tree instead?

**Comment by liangxin1300** [comment]
Yes, the migration tree based on https://github.com/liangxin1300/crmsh/commits/crmsh-py3
You can skip commit which commit message starts with "hb_report" firstly.

crmsh on py3 requires:
       lxml
       python3-curses
       PyYAML
       parallax
       py-dateutil(for hb_report)

**Comment by krig** [comment]
Thanks!

**Pull request merged**
